### ISSUE TITLE
JsonWebToken discussion

### ISSUE THREAD

**Issue by alex-nexus** [emaraschio/spowtify-api#2]
I see you using JsonWebToken. A couple questions: 
1. what would happen when the token expires?
2. I see you encode only user id into the token

**Comment by emaraschio** [comment]
1. If the token decoding fails (expiration or validation) `JsonWebToken` will raise an exception which will be handled in the `ExceptionHandler` module. It will be a 422 code -> Unprocessable Entity.
Rails has `rescue_from` approach to handle this kind of things and ussualy make a redirect to some path. Let me know if I need to add this feature on our `ExceptionHandler` module.

2. The token is: user_id and expires value, all encoded with `Rails.application.secrets.secret_key_base` throw `JWT` Library
What is your specific concern about that?

**Comment by alex-nexus** [comment]
ok
