### ISSUE TITLE
Data model discussion

### ISSUE THREAD

**Issue by alex-nexus** [emaraschio/spowtify-api#3]
1. I see several model having user on them. Can you explain what's usage for them?
2. I see an album belongs to an artist, and a song belongs to both artist and album. How would you handle if a song belongs an album thats different from the artist?
3. It seems album model is missing a relationship with songs

**Comment by emaraschio** [comment]
1. My Mistake, I removed it.

2. You are right, the song needs to be tied only to an album.

3. So I need to cover this scenario: A song can belong to some differents albums
Am I right? Note: this is a completly diffrente thing from playlits / playlists_songs

**Comment by alex-nexus** [comment]
3. yes. album is different from playlist. I was just pointing out that there was no association to songs on the album model.
