### ISSUE TITLE
Song API discussion

### ISSUE THREAD

**Issue by alex-nexus** [emaraschio/spowtify-api#4]
1. When deleting a song, how should its album or playlist be updated?
2. When deleting an album, how should the songs be handled?
3. How to adding / removing songs to album?

**Comment by emaraschio** [comment]
1. I think If you delete a song, it will removed from all the playlists.
2. TBD: Depends on #3 
3. TBD: Depends on #3

**Comment by alex-nexus** [comment]
ok
